const CODED_STRING = "qio qpbvmi fx bdla";
const KEY_LENGTH = 6;

import { Word, BRISPELL } from "@andsfonseca/palavras-pt-br";
Word.library = BRISPELL;

const allWords = Word.getAllWords(KEY_LENGTH, true, false, false, true);
const possibleKeys = allWords
  .filter((a) => a.length == KEY_LENGTH)
  .map((a) => a.toLowerCase());

// console.log(possibleKeys);

const getViginereDecodedItem = (keyChar, letter) => {
  const aCode = "a".charCodeAt();
  const zCode = "z".charCodeAt();

  const letterCode = letter.charCodeAt();
  const keyCode = keyChar.charCodeAt();

  const letterJumper = keyCode - aCode;

  let newCode = letterCode - letterJumper;

  if (newCode < aCode) newCode = zCode - (aCode - newCode - 1);

  return String.fromCharCode(newCode);
};

// possibleKeys
// const firstCoded = CODED_STRING.split(" ")[0];

// console.log(getViginereDecodedItem("x", "r"));
// console.log(CODED_STRING.split(" "));

let validPhrases = 0;
for (let i = 0; i < possibleKeys.length; i++) {
  if (i % (possibleKeys.length / 100).toFixed() == 0)
    console.log(`${i}/${possibleKeys.length}`);

  const k = possibleKeys[i].repeat(3);
  let decoded = "";
  let spacers = 0;
  let invalidPhrase = false;
  let isValid = false;

  for (let j = 0; j < CODED_STRING.length; j++) {
    if (CODED_STRING[j] == " ") {
      if (!isValid && !Word.checkValid(decoded.split(" ").pop())) {
        invalidPhrase = true;
        break;
      }

      spacers++;
      decoded = decoded.concat(" ");
      isValid = true;
    } else
      decoded = decoded.concat(
        getViginereDecodedItem(k[j - spacers], CODED_STRING[j])
      );
  }

  if (!invalidPhrase) console.log(decoded, validPhrases++);
}

console.log(validPhrases);
// possibleKeys.forEach((key) => {
//   let decoded = "";
//   let spacers = 0;

//   Array.from(CODED_STRING).forEach((l, i) => {
//     if (l == " ") {
//       spacers++;
//       decoded = decoded.concat(" ");
//     } else decoded = decoded.concat(getViginereDecodedItem(k[i - spacers], l));
//   });

//   const result = decoded
//     .map((_, i) => getViginereDecodedItem(firstCoded[i], key[i]))
//     .join("");

//   if (Word.checkValid(result)) console.log(key, result);
// });

// const keys = [
//   "bicaco",
//   "bicaco",
//   "bicais",
//   "bicama",
//   "bicame",
//   "bicane",
//   "bicaro",
//   "bicato",
//   "biceps",
//   "bichao",
//   "bichar",
//   "bichas",
//   "bichir",
//   "bichos",
//   "bicoco",
//   "bicoma",
//   "bicone",
//   "bicoso",
//   "bicuda",
//   "bicudo",
//   "bicula",
//   "bicuni",
//   "bidens",
//   "bidero",
//   "bideto",
//   "bidiao",
//   "bidino",
//   "biface",
//   "bifana",
//   "bifaro",
//   "bifero",
//   "bifida",
//   "bifido",
//   "bifilo",
//   "biflor",
//   "bifore",
//   "biforo",
//   "bigamo",
//   "bigate",
//   "bigato",
//   "bigene",
//   "bigode",
//   "bigodi",
//   "bigola",
//   "bigote",
//   "biguar",
//   "biguas",
//   "bigudi",
//   "bigume",
//   "biparo",
//   "bipede",
//   "bipene",
//   "biplex",
//   "bipolo",
//   "biraia",
//   "biraro",
//   "biriba",
//   "birica",
//   "birico",
//   "birifo",
//   "biriva",
//   "biroba",
//   "birola",
//   "biroro",
//   "birote",
//   "birrar",
//   "birros",
//   "biruba",
//   "cibalo",
//   "cibana",
//   "cibato",
//   "cibeia",
//   "cibele",
//   "cibico",
//   "cidada",
//   "cidade",
//   "cidade",
//   "cidaga",
//   "cidipe",
//   "cidoro",
//   "cidose",
//   "cidral",
//   "cidrao",
//   "ciecie",
//   "cieiro",
//   "ciente",
//   "cifato",
//   "cifela",
//   "cifose",
//   "cifrao",
//   "cifrar",
//   "cigana",
//   "cigano",
//   "cigude",
//   "cinara",
//   "cincao",
//   "cincar",
//   "cincia",
//   "cinclo",
//   "cindir",
//   "cinece",
//   "cinedo",
//   "cineia",
//   "cinema",
//   "cingel",
//   "cingir",
//   "cinico",
//   "cinipe",
//   "cinira",
//   "cintar",
//   "cintel",
//   "cintia",
//   "cintos",
//   "cintra",
//   "cinzar",
//   "cinzas",
//   "cinzel",
//   "cinzeo",
//   "cirano",
//   "cirata",
//   "circeu",
//   "circio",
//   "circum",
//   "cirene",
//   "cireno",
//   "cirial",
//   "cirilo",
//   "cirino",
//   "ciumar",
//   "cmliii",
//   "cmlvii",
//   "cmlxii",
//   "cmlxiv",
//   "cmlxix",
//   "cmlxvi",
//   "cmlxxi",
//   "cmlxxv",
//   "cmlxxx",
//   "didata",
//   "didimo",
//   "digama",
//   "digamo",
//   "digino",
//   "digite",
//   "digito",
//   "dignar",
//   "digono",
//   "diguti",
//   "dijica",
//   "dijina",
//   "dijole",
//   "dinaba",
//   "diname",
//   "dinamo",
//   "dindar",
//   "dindia",
//   "dindie",
//   "dindim",
//   "dinemo",
//   "dineto",
//   "dingui",
//   "dinico",
//   "dinodo",
//   "dinoio",
//   "dinope",
//   "dinora",
//   "dintel",
//   "diquia",
//   "ebiara",
//   "ecfora",
//   "echiao",
//   "eficaz",
//   "efigie",
//   "efilio",
//   "efipio",
//   "efireu",
//   "efitia",
//   "elcana",
//   "eliane",
//   "eliano",
//   "elicio",
//   "elidir",
//   "eliene",
//   "eliete",
//   "elifaz",
//   "eligio",
//   "eligir",
//   "elimas",
//   "elimeu",
//   "elimim",
//   "elinga",
//   "eliota",
//   "elipse",
//   "elisao",
//   "eliseu",
//   "eliseu",
//   "elisio",
//   "elisma",
//   "elissa",
//   "elitro",
//   "elixar",
//   "elixir",
//   "enocoa",
//   "enocto",
//   "enodar",
//   "enodio",
//   "enoema",
//   "enogar",
//   "enojar",
//   "enoleo",
//   "enomel",
//   "enopio",
//   "enoplo",
//   "enoque",
//   "enorme",
//   "enovar",
//   "epacmo",
//   "epacre",
//   "epacta",
//   "epalto",
//   "eparca",
//   "eparma",
//   "eroder",
//   "erodio",
//   "erodir",
//   "erosao",
//   "erosar",
//   "etolio",
//   "etomia",
//   "etonam",
//   "etopeu",
//   "eucare",
//   "eucata",
//   "eucero",
//   "eucles",
//   "eucome",
//   "exodio",
//   "exorar",
//   "exorca",
//   "ezrina",
//   "fibula",
//   "fieira",
//   "fieiro",
//   "fieito",
//   "filaca",
//   "filago",
//   "filali",
//   "filame",
//   "fileco",
//   "filele",
//   "fileno",
//   "filhao",
//   "filhar",
//   "filhas",
//   "filhos",
//   "filial",
//   "filiar",
//   "filica",
//   "filine",
//   "filipe",
//   "filite",
//   "filito",
//   "filmao",
//   "filmar",
//   "filmes",
//   "filode",
//   "filoma",
//   "filoso",
//   "filtro",
//   "filula",
//   "filuro",
//   "finado",
//   "finais",
//   "fincao",
//   "fincar",
//   "findar",
//   "findos",
//   "fineza",
//   "finfar",
//   "finfim",
//   "fingir",
//   "finice",
//   "finico",
//   "finito",
//   "finoto",
//   "fintao",
//   "fintar",
//   "finura",
//   "fisale",
//   "fisalo",
//   "fisaro",
//   "fiscal",
//   "fiscal",
//   "fiscia",
//   "fisema",
//   "fisese",
//   "fisgar",
//   "fisico",
//   "fisico",
//   "fisose",
//   "fissao",
//   "fissil",
//   "fistor",
//   "fistra",
//   "fitaca",
//   "fitato",
//   "fitico",
//   "fitina",
//   "fitona",
//   "fitose",
//   "fiunca",
//   "fiunco",
//   "himbar",
//   "himens",
//   "himera",
//   "himero",
//   "hirace",
//   "hirara",
//   "hireia",
//   "hirgol",
//   "hirieu",
//   "hirino",
//   "hirira",
//   "hiromi",
//   "hirpex",
//   "hirtar",
//   "hirtos",
//   "hirudo",
//   "iboicu",
//   "ictero",
//   "ictina",
//   "ictino",
//   "ictiol",
//   "idjogo",
//   "imagem",
//   "imanar",
//   "imanes",
//   "imarui",
//   "imazar",
//   "imbele",
//   "imbila",
//   "imbiua",
//   "imbora",
//   "imbote",
//   "imbuia",
//   "imbuim",
//   "imbuir",
//   "imburi",
//   "imelda",
//   "imenso",
//   "imerso",
//   "imisso",
//   "imitar",
//   "imitir",
//   "imutar",
//   "ixodio",
//   "ixoras",
//   "ixorea",
//   "izombe",
//   "jiboia",
//   "jibona",
//   "jibril",
//   "jibuti",
//   "jicara",
//   "jipepe",
//   "jipuba",
//   "libame",
//   "libano",
//   "libano",
//   "libata",
//   "libelo",
//   "libero",
//   "libico",
//   "libido",
//   "libita",
//   "libito",
//   "libolo",
//   "librar",
//   "libras",
//   "libreu",
//   "libris",
//   "libuno",
//   "lifemo",
//   "lifuco",
//   "lifuti",
//   "linale",
//   "lincar",
//   "linceo",
//   "lindar",
//   "lindas",
//   "lindos",
//   "lineal",
//   "linear",
//   "lineia",
//   "linete",
//   "linfar",
//   "lingao",
//   "lingar",
//   "lingel",
//   "lingre",
//   "lingua",
//   "linhal",
//   "linhao",
//   "linhar",
//   "linhas",
//   "linhol",
//   "linhos",
//   "linico",
//   "linina",
//   "linite",
//   "linoma",
//   "linose",
//   "lintea",
//   "lintel",
//   "lintia",
//   "linura",
//   "liraca",
//   "lirado",
//   "lirial",
//   "lirico",
//   "lirino",
//   "lirios",
//   "lirodo",
//   "lizela",
//   "lizusa",
//   "nifela",
//   "nifona",
//   "quiabo",
//   "quiaca",
//   "quiala",
//   "quiama",
//   "quiara",
//   "quiari",
//   "quibis",
//   "quiboa",
//   "quibua",
//   "quibus",
//   "quicai",
//   "quical",
//   "quicar",
//   "quicas",
//   "quicau",
//   "quices",
//   "quiche",
//   "quicio",
//   "quicoa",
//   "quicos",
//   "quicua",
//   "quidam",
//   "quiela",
//   "quiina",
//   "quiita",
//   "quilha",
//   "quilim",
//   "quilio",
//   "quilme",
//   "quiloa",
//   "quilos",
//   "quimao",
//   "quimau",
//   "quimes",
//   "quimia",
//   "quinal",
//   "quinar",
//   "quinas",
//   "quinau",
//   "quinca",
//   "quinda",
//   "quinim",
//   "quinio",
//   "quinoa",
//   "quinol",
//   "quinor",
//   "quinos",
//   "quinta",
//   "quinta",
//   "quinte",
//   "quinti",
//   "quinto",
//   "quinze",
//   "quinzo",
//   "quioco",
//   "quioio",
//   "quiota",
//   "quioto",
//   "quiova",
//   "quioza",
//   "quiper",
//   "quipiu",
//   "quiqui",
//   "quiral",
//   "quirao",
//   "quirdi",
//   "quirie",
//   "quirim",
//   "quirua",
//   "quisco",
//   "quispa",
//   "quisto",
//   "quitao",
//   "quitar",
//   "quitia",
//   "quitim",
//   "quiton",
//   "quitos",
//   "quitue",
//   "quitul",
//   "quixia",
//   "quorum",
//   "quotar",
//   "quotas",
//   "ribana",
//   "ribete",
//   "ribose",
//   "rifano",
//   "rifete",
//   "rififi",
//   "riflar",
//   "rizeco",
//   "rizino",
//   "rizodo",
//   "rizoma",
//   "rizopo",
//   "rizoto",
//   "rizula",
//   "scheol",
//   "sibala",
//   "sibana",
//   "sibara",
//   "sibele",
//   "sibilo",
//   "sibilu",
//   "sibine",
//   "sibira",
//   "sibivo",
//   "sidaga",
//   "sidamo",
//   "sideta",
//   "sidina",
//   "sidnei",
//   "sidney",
//   "sifile",
//   "siflar",
//   "sifneo",
//   "sifnio",
//   "sifula",
//   "sipaio",
//   "sipibo",
//   "sipiri",
//   "siraco",
//   "siracu",
//   "sirage",
//   "sirali",
//   "sirdar",
//   "sireca",
//   "sirgar",
//   "siriba",
//   "sirica",
//   "sirico",
//   "sirino",
//   "sirinx",
//   "siriri",
//   "sirito",
//   "sirixa",
//   "sirnio",
//   "siroco",
//   "sirote",
//   "sirrum",
//   "sitana",
//   "sitela",
//   "sitial",
//   "sitiar",
//   "sitico",
//   "sitida",
//   "sitite",
//   "sitito",
//   "sitona",
//   "sitone",
//   "situar",
//   "situla",
//   "tifale",
//   "tifico",
//   "tifoia",
//   "tifose",
//   "tifoso",
//   "tifula",
//   "tigela",
//   "tigelo",
//   "tiglao",
//   "tiglio",
//   "tigrao",
//   "tigres",
//   "tigura",
//   "tiraca",
//   "tiraco",
//   "tirada",
//   "tirado",
//   "tirana",
//   "tirana",
//   "tirano",
//   "tirape",
//   "tireia",
//   "tirete",
//   "tiriba",
//   "tirica",
//   "tirina",
//   "tirira",
//   "tiriri",
//   "tiriva",
//   "tiroma",
//   "uadada",
//   "uadico",
//   "uaeira",
//   "udotea",
//   "ufscar",
//   "ulrico",
//   "utinga",
//   "utopia",
//   "uvular",
//   "uxorio",
//   "uzifur",
//   "uzinho",
//   "vagado",
//   "vagear",
//   "vagens",
//   "vagina",
//   "vagite",
//   "vagito",
//   "vagner",
//   "vagoes",
//   "vagona",
//   "vagulo",
//   "viacao",
//   "viador",
//   "viagem",
//   "viagra",
//   "viajao",
//   "viajar",
//   "viajor",
//   "viamao",
//   "vianes",
//   "viante",
//   "viario",
//   "viasco",
//   "viavel",
//   "vibelo",
//   "vibero",
//   "vibice",
//   "vibora",
//   "vibrar",
//   "vibrio",
//   "vibute",
//   "vilaca",
//   "vileco",
//   "vilela",
//   "vileta",
//   "vileza",
//   "vilhar",
//   "viliar",
//   "villas",
//   "vilmar",
//   "viloca",
//   "viloma",
//   "vilosa",
//   "viloso",
//   "vilota",
//   "vilson",
//   "vilula",
//   "vinago",
//   "vinaia",
//   "vinato",
//   "vincar",
//   "vincio",
//   "vincos",
//   "vindas",
//   "vingar",
//   "vinhal",
//   "vinhao",
//   "vinhar",
//   "vinhas",
//   "vinhos",
//   "vinial",
//   "vinico",
//   "vinilo",
//   "vinion",
//   "vinola",
//   "vinoso",
//   "vintao",
//   "vintem",
//   "xibalo",
//   "xibara",
//   "xibaro",
//   "xibata",
//   "xibebe",
//   "xipaia",
//   "xipala",
//   "xipefo",
//   "xipene",
//   "xipoco",
//   "zibeao",
//   "zibeta",
//   "zidane",
//   "zifeus",
// ];

// keys.forEach((key) => {
//   // const k = key.repeat(3);
//   const k = "digono".repeat(3);

//   let decoded = "";
//   let spacers = 0;

//   Array.from(CODED_STRING).forEach((l, i) => {
//     if (l == " ") {
//       spacers++;
//       decoded = decoded.concat(" ");
//     } else decoded = decoded.concat(getViginereDecodedItem(k[i - spacers], l));
//   });

//   console.log(decoded);
// });

// console.log(Word.checkValid("teste"));
